/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class ConsoleClient {
  static builder(): ConsoleClientBuilder
  get mounts(): Array<string>
  start(): Promise<void>
  stop(): Promise<void>
  exec(cmd: Array<string>, timeoutMs?: number | undefined | null): Promise<ExecResult>
  read(path: string, offset?: number | undefined | null, len?: number | undefined | null): Promise<ReadResult>
  /** Put `data` in a file, settling with the file's size afterwards. */
  write(path: string, data: Buffer | string, offset?: number | undefined | null): Promise<number>
  snapshot(): Promise<Buffer>
  /** End the session now. Closing twice is the same as closing once. */
  close(): Promise<void>
}
export type JsConsoleClient = ConsoleClient

/**
 * A [`ConsoleClientBuilder`], filled in place and emptied by `build()`.
 *
 * In place rather than by value, unlike `Recipe`: the Rust builder is consumed by each call
 * and is not `Clone`, so there is exactly one of it to hand along. Each method returns the
 * same object so calls chain as they do in Rust.
 */
export declare class ConsoleClientBuilder {
  constructor()
  cmd(cmd: Array<string>): this
  mount(mount: HostMount | string, at: string): this
  mountReadonly(mount: HostMount | string, at: string): this
  image(image: ImageSource | Recipe): this
  snapshot(snapshot: Buffer): this
  network(network: boolean): this
  /**
   * Ports on the server's machine that lead into the session, as docker's `-p` spells
   * them: `"8080:80"`, host first.
   */
  ports(ports: Array<string>): this
  vcpus(vcpus: number): this
  memoryMib(memoryMib: number): this
  gpu(gpu: boolean): this
  gpuMemoryMib(gpuMemoryMib: number): this
  diskGib(diskGib: number): this
  /** Announce the session, and settle with the `ConsoleClient` the server answered. */
  build(): Promise<ConsoleClient>
}
export type JsConsoleClientBuilder = ConsoleClientBuilder

export declare class Directory {
  constructor()
  addFile(path: string, content: Buffer | string): void
  removeFile(path: string): void
  mount(path: string, hostDir: string): void
  unmount(path: string): void
  /** `addFile`, handing back this same `Directory` so calls chain. */
  withFile(path: string, content: Buffer | string): this
  /** `mount`, handing back this same `Directory` so calls chain. */
  withMount(path: string, hostDir: string): this
}
export type JsDirectory = Directory

/**
 * A tree mounted on this host, until `unmount` or until nothing holds it.
 *
 * Held behind an [`Arc`] so that passing one to a console builder does not take it from
 * the JavaScript object: both hold the mount, and without an `unmount` it comes down when
 * the last of them lets go — the builder's copy with the console, the JavaScript one with
 * garbage collection.
 *
 * **Garbage collection is not an exit.** Node runs no finalizer on `process.exit()`, and
 * none at all on a signal or a crash, so a mount left to one is taken down by virtx's
 * watchdog, from outside the process, once the process is gone. `unmount` is how a
 * program that wants it down *now* says so.
 */
export declare class HostMount {
  constructor(fs: Directory, mountpoint: string)
  get mountpoint(): string
  /**
   * Take the mount down now, and settle once it is down.
   *
   * Whoever else holds it — a console it was handed to — holds a mount point that is no
   * longer mounted from here on, so this belongs after the console using it is closed.
   * A second call, or one after the mount already came down, settles at once.
   *
   * Off the JavaScript thread: a guard comes down by unmounting and then waiting for the
   * thread serving it, which waits for every holder of the tree to let go.
   */
  unmount(): Promise<void>
}
export type JsHostMount = HostMount

export declare class ImageClient {
  /**
   * `virtx-uvm` under the stdio server directory, settling with the client once the
   * server has answered.
   */
  static tryNew(): Promise<ImageClient>
  static tryFromCmd(cmd: Array<string>): Promise<ImageClient>
  version(): Promise<string>
  build(recipe: Recipe, reference?: string | undefined | null): Promise<BuildImageResult>
  list(): Promise<Array<ImageEntry>>
  remove(image: ImageSource | Recipe): Promise<void>
  /** End the channel now. Closing twice is the same as closing once. */
  close(): Promise<void>
}
export type JsImageClient = ImageClient

export declare class ImageSource {
  static reference(reference: string): ImageSource
  static digest(digest: string): ImageSource
  static recipe(recipe: Recipe): ImageSource
  equals(other: ImageSource): boolean
  toString(): string
}
export type JsImageSource = ImageSource

export declare class Recipe {
  constructor(base: string, steps?: Array<Step | string>)
  static fromDockerfile(content: string): Recipe
  get base(): string
  step(step: Step | string): Recipe
  steps(steps: Array<Step | string>): Recipe
  equals(other: Recipe): boolean
  toString(): string
}
export type JsRecipe = Recipe

export declare class Step {
  static run(cmd: string): Step
  static copy(src: string, dst: string): Step
  static env(key: string, value: string): Step
  static workdir(dir: string): Step
  equals(other: Step): boolean
  toString(): string
}
export type JsStep = Step

export interface BuildImageResult {
  reference: string
  digest: string
}

/**
 * Fetch the console server into virtx's cache if it is not there, and settle with the
 * directory it is in.
 *
 * A server already there is left alone, whether it was fetched or installed by hand.
 */
export declare function ensureVirtx(): Promise<string>

export interface ExecResult {
  code: number
  stdout: Buffer
  stderr: Buffer
  truncated: boolean
}

export interface ImageEntry {
  digest: string
  refs: Array<string>
}

/**
 * Throw, saying what to install, if this host cannot mount.
 *
 * `HostMount` checks the same before it mounts, so this is for a caller that wants to know
 * ahead of asking for one. An addon built with `mount` loads on a host without the
 * provider: what a missing FUSE-T or Dokany costs is a mount, never the `require`.
 */
export declare function mountSupport(): void

export interface ReadResult {
  data: Buffer
  /** A JavaScript number, so exact up to 2^53 bytes. */
  size: number
}
