/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class ConsoleClient {
  static builder(): ConsoleClientBuilder
  get mounts(): Array<string>
  start(): Promise<void>
  stop(): Promise<void>
  exec(cmd: Array<string>, timeoutMs?: number | undefined | null): Promise<ExecResult>
  read(path: string, offset?: number | undefined | null, len?: number | undefined | null): Promise<ReadResult>
  /** Put `data` in a file, settling with the file's size afterwards. */
  write(path: string, data: Buffer | string, offset?: number | undefined | null): Promise<number>
  snapshot(): Promise<Buffer>
  /**
   * Answer one protocol frame on this console's channel, for an addon that drives this
   * session as a console of its own (see `virtx::console::Relay`); not for JavaScript
   * callers. Rejects when the channel is broken or this console closed, after which the
   * other side hears nothing more.
   */
  _relay(frame: Buffer): Promise<Buffer>
  /** End the session now. Closing twice is the same as closing once. */
  close(): Promise<void>
}
export type JsConsoleClient = ConsoleClient

/**
 * A [`ConsoleClientBuilder`], mutated in place (the Rust one is consumed per call and is not
 * `Clone`) and emptied by `build()`; every method returns this same object, so calls chain.
 */
export declare class ConsoleClientBuilder {
  constructor()
  cmd(cmd: Array<string>): this
  mount(mount: HostMount | string, at: string): this
  mountReadonly(mount: HostMount | string, at: string): this
  image(image: ImageSource | Recipe): this
  snapshot(snapshot: Buffer): this
  network(network: boolean): this
  /**
   * Ports on the server's machine that lead into the session, as docker's `-p` spells
   * them: `"8080:80"`, host first.
   */
  ports(ports: Array<string>): this
  vcpus(vcpus: number): this
  memoryMib(memoryMib: number): this
  gpu(gpu: boolean): this
  gpuMemoryMib(gpuMemoryMib: number): this
  diskGib(diskGib: number): this
  /** Announce the session to the server and settle with the resulting `ConsoleClient`. */
  build(): Promise<ConsoleClient>
}
export type JsConsoleClientBuilder = ConsoleClientBuilder

/**
 * A tree assembled in place. Mounting it with `HostMount` takes it: the mount owns the tree,
 * and this `Directory` is empty afterwards and refuses further use.
 */
export declare class Directory {
  constructor()
  addFile(path: string, content: Buffer | string): void
  removeFile(path: string): void
  mount(path: string, hostDir: string): void
  unmount(path: string): void
  /** `addFile`, returning this same `Directory` so calls chain. */
  withFile(path: string, content: Buffer | string): this
  /** `mount`, returning this same `Directory` so calls chain. */
  withMount(path: string, hostDir: string): this
}
export type JsDirectory = Directory

/**
 * A tree mounted on this host until `unmount()` or until nothing holds it.
 *
 * Passing it to a console builder shares it rather than taking it: without `unmount()` it
 * comes down when the last holder lets go (the builder's copy with the console, this object
 * with garbage collection).
 *
 * **Garbage collection is not an exit.** Node runs no finalizer on `process.exit()`, and none
 * on a signal or crash; a mount left to one is taken down from outside the process once it
 * is gone (by virtx's watchdog on unix, by Dokany on Windows). Call `unmount()` to take it
 * down *now*.
 */
export declare class HostMount {
  constructor(fs: Directory, mountpoint: string)
  get mountpoint(): string
  /**
   * Take the mount down now, and settle once it is down.
   *
   * Consoles it was handed to are left with an unmounted mount point, so call this after
   * closing them. A repeat call, or one after the mount already came down, settles at once.
   *
   * Runs off the JavaScript thread: dropping a guard unmounts and then waits for the thread
   * serving it, which waits for every holder of the tree to let go.
   */
  unmount(): Promise<void>
}
export type JsHostMount = HostMount

export declare class ImageClient {
  /** Start `virtx-uvm` from virtx's cache `bin`; settles once the server answers. */
  static tryNew(): Promise<ImageClient>
  static tryFromCmd(cmd: Array<string>): Promise<ImageClient>
  version(): Promise<string>
  build(recipe: Recipe, reference?: string | undefined | null): Promise<BuildImageResult>
  list(): Promise<Array<ImageEntry>>
  remove(image: ImageSource | Recipe): Promise<void>
  /** End the channel now. Closing twice is the same as closing once. */
  close(): Promise<void>
}
export type JsImageClient = ImageClient

export declare class ImageSource {
  static reference(reference: string): ImageSource
  static digest(digest: string): ImageSource
  static recipe(recipe: Recipe): ImageSource
  equals(other: ImageSource): boolean
  toString(): string
}
export type JsImageSource = ImageSource

export declare class Recipe {
  constructor(base: string, steps?: Array<Step | string>)
  static fromDockerfile(content: string): Recipe
  get base(): string
  step(step: Step | string): Recipe
  steps(steps: Array<Step | string>): Recipe
  equals(other: Recipe): boolean
  toString(): string
}
export type JsRecipe = Recipe

export declare class Step {
  static run(cmd: string): Step
  static copy(src: string, dst: string): Step
  static env(key: string, value: string): Step
  static workdir(dir: string): Step
  equals(other: Step): boolean
  toString(): string
}
export type JsStep = Step

export interface BuildImageResult {
  reference: string
  digest: string
}

/**
 * Fetch the console server into virtx's cache if missing, and settle with its directory.
 *
 * Console builders and `ImageClient` start `virtx-uvm` from that cache, which a host that
 * installed only this package lacks, so such a host calls this first. An existing server,
 * fetched or installed by hand, is left alone.
 */
export declare function ensureVirtx(): Promise<string>

export interface ExecResult {
  code: number
  stdout: Buffer
  stderr: Buffer
  truncated: boolean
}

export interface ImageEntry {
  digest: string
  refs: Array<string>
}

/**
 * Throw, saying what to install, if this host cannot mount.
 *
 * `HostMount` checks the same before mounting; this lets a caller find out ahead. An addon
 * built with `mount` still loads without FUSE-T or Dokany: only mounting fails, never `require`.
 */
export declare function mountSupport(): void

export interface ReadResult {
  data: Buffer
  /** A JavaScript number, so exact up to 2^53 bytes. */
  size: number
}
